(() => {
  // <stdin>
  document.addEventListener("DOMContentLoaded", () => {
    const btn = document.getElementById("scrollTopBtn");
    window.addEventListener("scroll", () => {
      if (window.scrollY > 150) {
        btn.classList.remove("hidden");
      } else {
        btn.classList.add("hidden");
      }
    });
    btn.addEventListener("click", () => {
      window.scrollTo({ top: 0, behavior: "smooth" });
    });
  });
  console.log("This site was generated by Hugo.");
})();
